import React, { useState, useRef } from 'react';
import { Calendar, X } from 'lucide-react';
import toast from 'react-hot-toast';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const ReportsTab: React.FC = () => {
  const [reportType, setReportType] = useState('Pending Fees Report');
  const [academicYear, setAcademicYear] = useState('2025-26');
  const [semester, setSemester] = useState('Semester 6');
  
  // Date states
  const [startDate, setStartDate] = useState('2026-03-01');
  const [endDate, setEndDate] = useState('2026-03-30');

  // Input Refs for interactive calendar triggering
  const startDateRef = useRef<HTMLInputElement>(null);
  const endDateRef = useRef<HTMLInputElement>(null);

  const [isSearching, setIsSearching] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [isPdfModalOpen, setIsPdfModalOpen] = useState(false);

  // Result records matching Figma design exactly
  const SEARCH_RESULTS = [
    { enrollmentNo: 'vu4s2425001', studentName: 'xyz', semester: 'Sem 6', totalFees: '2100', paidAmount: '2100', pendingAmount: '0', status: 'Confirmed' },
    { enrollmentNo: 'vu4s2526142', studentName: 'abc', semester: 'Sem 4', totalFees: '1500', paidAmount: '500', pendingAmount: '1000', status: 'Pending' }
  ];

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    setIsSearching(true);
    setTimeout(() => {
      setIsSearching(false);
      setShowResults(true);
      toast.success(`Search completed! Found 2 records.`);
    }, 800);
  };

  const handleExportPdf = () => {
    setIsPdfModalOpen(true);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("XYZ AUTONOMOUS INSTITUTE", 105, 15, { align: "center" });

    doc.setFontSize(12);
    doc.text("Report type: Pending Fees Report", 14, 25);

    // Box details
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    
    doc.rect(14, 30, 182, 45);
    doc.text("Academic Year : 2025-26", 18, 38);
    doc.text("Semester : Semester 6", 18, 44);
    doc.text("Date Range : 01-03-2026 to 30-03-2026", 18, 50);
    doc.text("Branch: Computer", 18, 56);
    doc.text("Generated By : COE Admin", 18, 62);
    doc.text("Generated On : 30-03-2026 11:45 AM", 18, 68);

    const tableColumn = ["Sr. No", "Student name", "Enrollment No", "Tution fees", "Paid Amount", "Balance", "Status"];
    const tableRows = [
      ["1.", "xyz", "vu4s2425001", "2100", "2100", "0", "Fully paid"],
      ["2.", "abc", "vu4s2526142", "1500", "500", "1000", "pending"]
    ];

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 85,
      styles: { halign: 'center', valign: 'middle' },
      headStyles: { fillColor: [249, 250, 251], textColor: [71, 84, 103], fontStyle: 'bold' },
    });

    doc.save("Pending_Fees_Report.pdf");
    toast.success('Report successfully downloaded!');
    setIsPdfModalOpen(false);
  };

  return (
    <div className="w-full flex flex-col gap-6 font-['Instrument_Sans'] select-none">
      
      {/* ── Reports Generation Form (EXACT alignment with Figma) ── */}
      <form onSubmit={handleSearch} className="flex flex-col gap-5 bg-white border border-[#e4e7ec] rounded-2xl p-8 shadow-xs">
        
        {/* 1. Select Report Type */}
        <div className="flex flex-col gap-1.5 w-full">
          <label className="text-[14px] font-semibold text-[#344054]">Select Report Type</label>
          <div className="relative">
            <select
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
              className="w-full px-3.5 py-3 bg-white border border-[#d0d5dd] rounded-lg text-[14px] text-[#101828] focus:outline-none focus:ring-4 focus:ring-[#0e1680]/5 focus:border-[#0e1680] shadow-xs appearance-none cursor-pointer"
            >
              <option value="Pending Fees Report">Pending Fees Report</option>
              <option value="Paid Fees Summary">Paid Fees Summary</option>
              <option value="Offline Payments Ledger">Offline Payments Ledger</option>
              <option value="Defaulters List">Defaulters List</option>
            </select>
            <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none text-[#667085]">
              <svg width="12" height="8" viewBox="0 0 12 8" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M1 1L6 6L11 1" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </div>
          </div>
        </div>

        {/* 2. Academic Year */}
        <div className="flex flex-col gap-1.5 w-full">
          <label className="text-[14px] font-semibold text-[#344054]">Academic Year</label>
          <input
            type="text"
            value={academicYear}
            onChange={(e) => setAcademicYear(e.target.value)}
            className="w-full px-3.5 py-3 bg-white border border-[#d0d5dd] rounded-lg text-[14px] text-[#101828] focus:outline-none focus:ring-4 focus:ring-[#0e1680]/5 focus:border-[#0e1680] shadow-xs transition-all"
          />
        </div>

        {/* 3. Semester */}
        <div className="flex flex-col gap-1.5 w-full">
          <label className="text-[14px] font-semibold text-[#344054]">Semester</label>
          <input
            type="text"
            value={semester}
            onChange={(e) => setSemester(e.target.value)}
            className="w-full px-3.5 py-3 bg-white border border-[#d0d5dd] rounded-lg text-[14px] text-[#101828] focus:outline-none focus:ring-4 focus:ring-[#0e1680]/5 focus:border-[#0e1680] shadow-xs transition-all"
          />
        </div>

        {/* 4. Start Date & End Date split grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5 w-full">
          {/* Start Date */}
          <div className="flex flex-col gap-1.5 w-full">
            <label className="text-[14px] font-semibold text-[#344054]">Start Date</label>
            <div className="relative">
              <input
                ref={startDateRef}
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                onClick={() => {
                  try {
                    startDateRef.current?.showPicker();
                  } catch (err) {}
                }}
                className="w-full pl-3.5 pr-10 py-3 bg-white border border-[#d0d5dd] rounded-lg text-[14px] text-[#101828] focus:outline-none focus:ring-4 focus:ring-[#0e1680]/5 focus:border-[#0e1680] shadow-xs transition-all cursor-pointer [&::-webkit-calendar-picker-indicator]:absolute [&::-webkit-calendar-picker-indicator]:inset-0 [&::-webkit-calendar-picker-indicator]:opacity-0 [&::-webkit-calendar-picker-indicator]:cursor-pointer"
              />
              <div 
                onClick={() => {
                  try {
                    startDateRef.current?.showPicker();
                  } catch (err) {}
                }}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-[#667085] hover:text-[#0e1680] cursor-pointer pointer-events-none"
              >
                <Calendar size={18} />
              </div>
            </div>
          </div>

          {/* End Date */}
          <div className="flex flex-col gap-1.5 w-full">
            <label className="text-[14px] font-semibold text-[#344054]">End Date</label>
            <div className="relative">
              <input
                ref={endDateRef}
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                onClick={() => {
                  try {
                    endDateRef.current?.showPicker();
                  } catch (err) {}
                }}
                className="w-full pl-3.5 pr-10 py-3 bg-white border border-[#d0d5dd] rounded-lg text-[14px] text-[#101828] focus:outline-none focus:ring-4 focus:ring-[#0e1680]/5 focus:border-[#0e1680] shadow-xs transition-all cursor-pointer [&::-webkit-calendar-picker-indicator]:absolute [&::-webkit-calendar-picker-indicator]:inset-0 [&::-webkit-calendar-picker-indicator]:opacity-0 [&::-webkit-calendar-picker-indicator]:cursor-pointer"
              />
              <div 
                onClick={() => {
                  try {
                    endDateRef.current?.showPicker();
                  } catch (err) {}
                }}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-[#667085] hover:text-[#0e1680] cursor-pointer pointer-events-none"
              >
                <Calendar size={18} />
              </div>
            </div>
          </div>
        </div>

        {/* Action Buttons aligned right (EXACT gap and layout from Figma) */}
        <div className="flex justify-end gap-[50px] items-center mt-[15px]">
          {/* Search Button */}
          <button
            type="submit"
            disabled={isSearching || isExporting}
            className="flex items-center justify-center gap-2 px-6 py-3 bg-[#0b0f4d] hover:bg-blue-900 text-white text-[14px] font-semibold rounded-lg shadow-sm focus:ring-4 focus:ring-[#0b0f4d]/20 transition-all disabled:bg-gray-300 disabled:cursor-not-allowed min-w-[86px] h-[44px] cursor-pointer"
          >
            {isSearching ? (
              <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
            ) : null}
            <span>Search</span>
          </button>

          {/* Export pdf Button */}
          <button
            type="button"
            onClick={handleExportPdf}
            disabled={isSearching || isExporting}
            className="flex items-center justify-center gap-2 px-6 py-3 bg-[#0b0f4d] hover:bg-blue-900 text-white text-[14px] font-semibold rounded-lg shadow-sm focus:ring-4 focus:ring-[#0b0f4d]/20 transition-all disabled:bg-gray-300 disabled:cursor-not-allowed min-w-[124px] h-[44px] cursor-pointer"
          >
            {isExporting ? (
              <svg className="animate-spin h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
              </svg>
            ) : null}
            <span>Export pdf</span>
          </button>
        </div>
      </form>

      {/* ── Searched result Table Section (EXACT alignment with Figma node-id 15695:150616) ── */}
      {showResults && (
        <div className="flex flex-col gap-4 w-full animate-in fade-in duration-300 mt-2">
          <h4 className="text-[20px] font-semibold text-[#1d2939]">Searched result</h4>
          
          <div className="bg-white border border-[#e4e7ec] rounded-2xl overflow-hidden shadow-xs">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-[#f9fafb] border-b border-[#e4e7ec]">
                    <th className="px-8 py-5 text-[12px] font-bold uppercase tracking-wider text-[#667085]">Enrollment No</th>
                    <th className="px-8 py-5 text-[12px] font-bold uppercase tracking-wider text-[#667085]">Student name</th>
                    <th className="px-8 py-5 text-[12px] font-bold uppercase tracking-wider text-[#667085]">Semester</th>
                    <th className="px-8 py-5 text-[12px] font-bold uppercase tracking-wider text-[#667085]">Total fees</th>
                    <th className="px-8 py-5 text-[12px] font-bold uppercase tracking-wider text-[#667085]">Paid Amount</th>
                    <th className="px-8 py-5 text-[12px] font-bold uppercase tracking-wider text-[#667085]">Pending Amount</th>
                    <th className="px-8 py-5 text-[12px] font-bold uppercase tracking-wider text-[#667085]">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#e4e7ec] text-[#344054]">
                  {SEARCH_RESULTS.map((row, idx) => (
                    <tr key={idx} className="hover:bg-gray-50/50 transition-colors h-[72px]">
                      <td className="px-8 py-6 text-[15px] font-medium text-[#101828]">
                        {row.enrollmentNo}
                      </td>
                      <td className="px-8 py-6 text-[15px] font-medium">
                        {row.studentName}
                      </td>
                      <td className="px-8 py-6 text-[15px] font-medium">
                        {row.semester}
                      </td>
                      <td className="px-8 py-6 text-[15px] font-medium">
                        {row.totalFees}
                      </td>
                      <td className="px-8 py-6 text-[15px] font-medium">
                        {row.paidAmount}
                      </td>
                      <td className="px-8 py-6 text-[15px] font-medium">
                        {row.pendingAmount}
                      </td>
                      <td className="px-8 py-6 text-[15px] font-medium">
                        <span className={`inline-flex items-center text-[14px] font-medium ${
                          row.status === 'Confirmed' ? 'text-green-700' : 'text-amber-700'
                        }`}>
                          {row.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* ── Export PDF Modal Overlay ── */}
      {isPdfModalOpen && (
        <div className="fixed inset-0 bg-black/40 backdrop-blur-xs flex items-center justify-center z-50 p-4 animate-in fade-in duration-200">
          <div className="bg-white rounded-2xl w-full max-w-[800px] shadow-xl overflow-hidden animate-in zoom-in-95 duration-200">
            <div className="p-8 flex flex-col gap-6 relative">
              <button 
                onClick={() => setIsPdfModalOpen(false)}
                className="absolute top-4 right-4 p-1 text-gray-500 hover:bg-gray-100 rounded-lg transition-colors cursor-pointer"
              >
                <X size={20} />
              </button>

              <div className="text-center">
                <h2 className="text-[18px] font-bold text-[#1d2939] uppercase tracking-wide">
                  XYZ AUTONOMOUS INSTITUTE
                </h2>
              </div>

              <div className="flex flex-col gap-3">
                <h3 className="text-[16px] font-bold text-[#344054]">
                  Report type: Pending Fees Report
                </h3>

                <div className="border border-[#e4e7ec] rounded-xl p-5 flex flex-col gap-2.5 text-[14px] text-[#475467]">
                  <p>Academic Year : 2025-26</p>
                  <p>Semester : Semester 6</p>
                  <p>Date Range : 01-03-2026 to 30-03-2026</p>
                  <p>Branch: Computer</p>
                  <p>Generated By : COE Admin</p>
                  <p>Generated On : 30-03-2026 11:45 AM</p>
                </div>
              </div>

              <div className="bg-white border border-[#e4e7ec] rounded-xl overflow-hidden">
                <table className="w-full text-center border-collapse">
                  <thead>
                    <tr className="bg-[#f9fafb] border-b border-[#e4e7ec]">
                      <th className="py-4 text-[13px] font-semibold text-[#667085]">Sr. No</th>
                      <th className="py-4 text-[13px] font-semibold text-[#667085]">Student name</th>
                      <th className="py-4 text-[13px] font-semibold text-[#667085]">Enrollment No</th>
                      <th className="py-4 text-[13px] font-semibold text-[#667085]">Tution fees</th>
                      <th className="py-4 text-[13px] font-semibold text-[#667085]">Paid Amount</th>
                      <th className="py-4 text-[13px] font-semibold text-[#667085]">Balance</th>
                      <th className="py-4 text-[13px] font-semibold text-[#667085]">Status</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#e4e7ec]">
                    <tr>
                      <td className="py-4 text-[14px] text-[#475467]">1.</td>
                      <td className="py-4 text-[14px] text-[#475467]">xyz</td>
                      <td className="py-4 text-[14px] text-[#475467]">vu4s2425001</td>
                      <td className="py-4 text-[14px] text-[#475467]">2100</td>
                      <td className="py-4 text-[14px] text-[#475467]">2100</td>
                      <td className="py-4 text-[14px] text-[#475467]">0</td>
                      <td className="py-4">
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[12px] font-semibold bg-green-100 text-green-800 border border-green-200">
                          Fully paid
                        </span>
                      </td>
                    </tr>
                    <tr>
                      <td className="py-4 text-[14px] text-[#475467]">2.</td>
                      <td className="py-4 text-[14px] text-[#475467]">abc</td>
                      <td className="py-4 text-[14px] text-[#475467]">vu4s2526142</td>
                      <td className="py-4 text-[14px] text-[#475467]">1500</td>
                      <td className="py-4 text-[14px] text-[#475467]">500</td>
                      <td className="py-4 text-[14px] text-[#475467]">1000</td>
                      <td className="py-4">
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[12px] font-semibold bg-orange-100 text-orange-800 border border-orange-200">
                          pending
                        </span>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <div className="flex justify-end pt-2">
                <button
                  onClick={handleDownloadPDF}
                  className="px-8 py-2.5 bg-[#0E1680] hover:bg-blue-900 text-white font-semibold rounded-lg shadow-sm focus:ring-4 focus:ring-[#0E1680]/20 transition-all cursor-pointer"
                >
                  Download
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
